### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by olabini** [twtiger/enigmail#1]
- Make sure tests all work
- Make sure eshint is installed and docker/vagrant works

**Comment by rosatolen** [comment]
It seems like the docker and vagrant setup may not be maintained by those who run the enigmail project. I have fixed the docker setup because we're using it on the team, but do we want to update vagrant even though it will probably fall out of date?

**Comment by rosatolen** [comment]
It seems like the docker and vagrant setup are not maintained by the enigmail community. I've fixed the docker setup because we are using it on the team, but do we want to keep vagrant as well, given that it may fall out of date?
