### ISSUE TITLE
Check for torify and torsocks

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#13]
On initialization, we should check if the user has torify or torsocks installed. 

If the user's version of GPG doesn't support the necessary version of curl to do key refresh over a proxy, and the user has torsocks or torify installed, then we should do a lookup over these.

(The order of these can be change, but most likely torsocks/torify will be an edge case, whereas more users will have gpg that supports lookups over a proxy)

**Comment by rosatolen** [comment]
added to #18 for clarity
