### ISSUE TITLE
Check version of GPG for a user

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#15]
This might help us understand whether we are able to do a key refresh lookup over a socks proxy for this user.

**Comment by chelseakomlo** [comment]
Most recent versions of gpg, there is the option --use-tor

https://www.gnupg.org/blog/20151103-gnupg-in-october.html

**Comment by olabini** [comment]
Chelsea, as I mentioned several times last week, use-tor is an option for dirmngr, not for gpg - and is useless to us.

**Comment by chelseakomlo** [comment]
Right, because you have to restart dirmngr, and we don't want to do that. Thanks @olabini !
