### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#17]
Setup Enigmail locally with the latest build and check for errors in refresh service.

Please be strict.
- Test continuous key refresh on different operating systems
- Test continuous key refresh using different versions of gpg
- Test continuous key refresh using Tor. Test with tor running on each of the default ports.
- Test using torsocks, torsocks2, torify, usewithtor

**Comment by yakiradixon** [comment]
Linking to the Enigmail development environment information from the wiki: https://sourceforge.net/p/enigmail/wiki/Development%20Environment/

**Comment by chelseakomlo** [comment]
We should probably also QA that if a user has something like: 
. /usr/bin/torsocks on
set, then the behavior is the same when we use the executables again in the query.
