### ISSUE TITLE
Use tor to refresh keys

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#18]
1. use proxy xpcom to check if tor is running properly
2. then make key request over tor

to make a key request over tor...
1. if version of gpg is good enough, use gpg curl to request key refresh over tor
2. else check for torsocks and use
3. else if user doesn't care about strict connect over tor then don't use tor

We should also create a new Tor circuit for each key refresh.

**Comment by chelseakomlo** [comment]
resolvePath in files.jsm can be helpful for checking if torify or torsocks is available

**Comment by chelseakomlo** [comment]
Need to investigate whether we should have cases where we use socks4 instead of socks5

**Comment by chelseakomlo** [comment]
Also, in what cases should we ever use the "gpg --use-tor" option? We could be simple and always use "http-proxy=socks5-hostname://127.0.0.1:9050" if this is supported in both newer and older versions...

**Comment by yakiradixon** [comment]
@chelseakomlo What is this reason we should investigate using SOCKS4 instead of SOCKS5?

**Comment by rosatolen** [comment]
@chelseakomlo can you pass us the link for the gpg --use-tor ability? thanks

**Comment by rosatolen** [comment]
we can't use the --use-tor option. details in #15

**Comment by olabini** [comment]
As I mentioned before, socks5-hostname doesn't work on all gpgs - in some cases you need to use socks5h instead .
