### ISSUE TITLE
utilize errorHandling.jsm for gpg responses

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#19]
gpgResponseParser.jsm will only handle error responses from GPG in English. 

We need to parse gpg error responses because if we fail at making a hkps request, we want to try hkp or we want to try another server in hkps. 

We want to be able to respond to messages in other languages that GPG may be using, or we want to be able to force a certain language for this single request so that our application reaction is consistent, or use GPG's exit codes... (whatever the implementer finds is easier).

**Comment by chelseakomlo** [comment]
We need to investigate whether IMPORT_OK is the same across all languages

**Comment by chelseakomlo** [comment]
IMPORT_OK is a status code, so it won't ever be translated. 

Other applications use it for interpreting GPG responses as well: 

https://github.com/lafisrap/enigmail/blob/72d55664cd21c870ed5ea67994cd6b8855b3ec6a/package/tests/errorHandling-test.js
