### ISSUE TITLE
Investigate Torsocks across different OSs

### ISSUE THREAD

**Issue by natalieesk** [twtiger/enigmail#2]
- We need to make sure it can run across all the OSs Thunderbird runs on

**Comment by chelseakomlo** [comment]
@olabini question- the number of users that have torsocks installed is small. We were thinking to include this as an dependency that would be installed on installing enigmail. Any arguments against this?

**Comment by olabini** [comment]
How would you include it as a dependency? Would you precompile it for all operating systems that Enigmail ships to? What would you do if there's an update of Torsocks? Force Enigmail to ship a new version? Did you investigate using Tor without Torsocks for GPG lookups?

In general, I'm quite against it, and I think it will be a hard sell to Nico and Patrick.

**Comment by chelseakomlo** [comment]
Yes, I had the exact same questions as you mention here. 

Will investigate using Tor without Torsocks tomorrow, I think will probably is a better option given how few people seem to have Tor installed, much less Torsocks.

**Comment by chelseakomlo** [comment]
Ok, we were looking at how tor is detected in Coy. This is the approach we think might be the best to take, let us know if you have other ideas @olabini
