### ISSUE TITLE
Check for other tor binaries and use if available

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#22]
torsocks (already have)
torsocks2
torify
usewithtor

**Comment by chelseakomlo** [comment]
Torify: since 0.2.4, is a wrapper around torsocks. 

http://apt-browse.org/browse/ubuntu/trusty/universe/i386/tor/0.2.4.20-1/

**Comment by chelseakomlo** [comment]
usewithtor: ubuntu 14.04, torsocks 1.3-3

http://manpages.ubuntu.com/manpages/trusty/man1/usewithtor.1.html

Uses the default configuration, while torsocks doesn't use a config file, unless it is manually set.

**Comment by chelseakomlo** [comment]
@olabini Do you have more info on torsocks2, where it is defined?

**Comment by olabini** [comment]
A lot of people compiled version 2 of torsocks as torsocks2, in order to be able to use both version 1 and 2.

**Comment by chelseakomlo** [comment]
Got it, thanks.

@olabini, why specifically would you want to support both version 1 and 2 on the same machine?

**Comment by chelseakomlo** [comment]
Ok, one difference between torsocks 1 and 2 is how a username/password is set: 

We are currently supporting torsocksv2: https://github.com/dgoulet/torsocks/blob/master/doc/torsocks.1#L40

Here is how torsocksv1 handles this: 
https://github.com/dgoulet/torsocks/blob/master/doc/torsocks.8#L88

**Comment by chelseakomlo** [comment]
Parsimonie does this: https://github.com/dgoulet/torsocks/blob/7969b543b292b43cdc6e7d9ad8af4f05cb5989b5/doc/torsocks.conf#L21
