### ISSUE TITLE
We define preferences for using/requiring Tor for searching for keys and uploading keys but do not use these preferences to construct arguments in the keyserver

### ISSUE THREAD

**Issue by yakiradixon** [twtiger/enigmail#28]

**Comment by chelseakomlo** [comment]
Is this the same as issue #23 ?

**Comment by yakiradixon** [comment]
It's related.

**Comment by rosatolen** [comment]
We will postpone using or requiring Tor for other actions (searching, uploading, refresh all keys...) until we have a conversation with the Enigmail team.
