### ISSUE TITLE
Unused Tor Helpers

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#31]
useWithTor is a wrapper around torsocks. 
So we probably shouldn't support useWithTor, as we can just use torsocks directly. 

http://manpages.ubuntu.com/manpages/trusty/man1/usewithtor.1.html

@olabini thoughts on this?

**Comment by yakiradixon** [comment]
torify and usewithtor are wrappers around torsocks, but we need to check if torsocks is available on a machine using all of the wrapper names.

**Comment by chelseakomlo** [comment]
Sure, that's fine. 

usewithtor is on ubuntu 14.04 and below.

**Comment by chelseakomlo** [comment]
usewithtor and torify both have the same interfaces to torsocks.
