### ISSUE TITLE
Check version for underlying torsocks when using torify and usewithtor helpers

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#33]

**Comment by rosatolen** [comment]
If torsocks doesn't exist, then we won't use torify or usewithtor. We shouldn't use tsocks in place of torsocks because it was deprecated due to security issues. So if torsocks or torsocks2 doesn't exist, we should use gpg2 proxy options.

**Comment by chelseakomlo** [comment]
We should still probably check for usewithtor as this has different
behavior than calling torsocks directly.
On Jul 8, 2016 11:26 AM, "rosatolen" notifications@github.com wrote:

If torsocks doesn't exist, then we won't use torify or usewithtor. We
shouldn't use tsocks in place of torsocks because it was deprecated due to
security issues. So if torsocks or torsocks2 doesn't exist, we should use
gpg2 proxy options.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/twtiger/enigmail/issues/33#issuecomment-231405713, or mute
the thread
https://github.com/notifications/unsubscribe/ACabc1eLnWP8YNjq6Zw7GyI4jSMVkI79ks5qTnodgaJpZM4JIHMM
.
