### ISSUE TITLE
Tor with gpg versions over 2.1.x on Mac OSX

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#37]
On gpg versions 2.1.x and up, socks5 proxy settings cannot be used to interact with tor. 

Right now we search for gpg-connect-agent to check whether or not gpg tor mode is enabled. We look in the regular path environment variable, but this will not work on Macs since they can have these packages installed in the /usr/local folder.

You can install gpg on a Mac using the GPGTools package or through brew. GnuPG modern (2.1) install dirmngr.

**Comment by rosatolen** [comment]
GPGTools's 2016.07 release contains GPG 2.0.30. In order to get a download of GnuPG modern to test for this issue, go here: https://gnupg.org/download/index.html

**Comment by chelseakomlo** [comment]
For others who want to test, you can install using: 

brew install homebrew/versions/gnupg21

**Comment by chelseakomlo** [comment]
Is broken. I am fixing.
