### ISSUE TITLE
Tor with gpg versions over 2.1.x on Windows

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#39]
On gpg versions 2.1.x and up, socks5 proxy settings cannot be used to interact with tor. Please enable us to use Tor the best we can on Windows if the version is over 2.1.x.

**Comment by rosatolen** [comment]
Gpg 2.1.14 is available here for download and verification: https://gnupg.org/download/index.html

Let's get this done. :dancer:

**Comment by chelseakomlo** [comment]
@yakiradixon you tested this on Windows, no? And everything looked ok?

**Comment by yakiradixon** [comment]
I've been testing on Windows today but I haven't tried using a version of gpg greater that 2.1.x to test that dirmngr and Tor Mode work. I have version 2.0.30. Maybe I'm missing it completely in my searches or in the link above but can someone point me to a  gpg 2.1 Windows binary release?
