### ISSUE TITLE
Correct the address to the pool of hkps sks-keyservers

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#41]
With ArchLinux and GPG version 2.1.13, requests to the hkps address hkps://pool.sks-keyservers.net fail for the following reason:

```
[GNUPG:] FAILURE recv-keys 167804976
gpg: keyserver receive failed: Invalid argument
```

hkps://pool.sks-keyservers.net is the hkps address we create to correspond with the following hkp address: pool.sks-keyservers.net

Instead of using hkps://pool.sks-keyservers.net, we should use either of the following addresses:
hkps.pool.sks-keyservers.net
hkps://hkps.pool.sks-keyservers.net:443

Reference: https://sks-keyservers.net/overview-of-pools.php

**Comment by rosatolen** [comment]
Addressed in this commit: 363acd8aace2102790e213e8032cddb25b4c4d2c 

Needs QA on Windows, Mac, and Ubuntu.

**Comment by chelseakomlo** [comment]
This fails on Mac with version of gpg > 2.1. Should this pass if the user hasn't configured anything specifically on their machine?

**Comment by chelseakomlo** [comment]
I get this on Mac: 
[GNUPG:] FAILURE recv-keys 1
gpg: keyserver receive failed: General error

Not very helpful.
