### ISSUE TITLE
Update way we order the keyservers for requests

### ISSUE THREAD

**Issue by natalieesk** [twtiger/enigmail#44]
Run through the keyservers in the order as presented, using hkps only when no protocol is specified. If all that fails, try hkp on keyservers with no protocol specified.

e.g. If given: keyserver1, hkps://keyserver2, hkp://keyserver3, keyserver4

Order them as follows:
hkps://keyserver1, hkps://keyserver2, hkp://keyserver3, hkps://keyserver4, hkp://keyserver1, hkp://keyserver4

Questions:
- Should we display this ordering to the user so they can understand that the order of their keyservers matters?

**Comment by natalieesk** [comment]
Updated decision:

We will prioritise the keyserver order over whether it's hkps or hkp. So that would return:
hkps://keyserver1, hkp://keyserver1, hkps://keyserver2, hkp://keyserver3, hkps://keyserver4,  hkp://keyserver4
(Note we try hkp with keyserver1 before continuing with the next specified keyserver).

**Comment by chelseakomlo** [comment]
This part is done, right?
