### ISSUE TITLE
Don't use invalid protocols that a user has defined in userPrefs

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#45]
If a user defines: hkps://someKeyserver:556, we _should_ use this

But: 

If a user defines: xyz://someKeyserver:443, we _shouldn't_ use it

**Comment by rosatolen** [comment]
Behavior specification: 

If some invalid protocols are specified in the keyserver list, we will ignore them completely. We will only make calls over the protocols hkps, hkp, and ldap (if specified). If no protocol is specified, we will use hkps and then hkp if this fails. Also, if the user does not specify any valid protocols, we will check their keyserver list again in an hour.

For example, in the cases where:
1. [xyz://someKeyserver:443, abc://somekeyserver:443]
The user won't have any valid keyservers, and the key refresh service will recheck in 1 hr. We will make a debug log that we haven't found any keyservers and we will retry.
2. [someKeyserver:443, abc://otherkeyserver:443] 
The user will have one valid keyserver. We will ignore the "otherkeyserver" with the "abc" protocol. We will make a debug log that we are ignoring the invalid protocol.

**Comment by chelseakomlo** [comment]
I think this can be closed?
