### ISSUE TITLE
Testing Windows

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#47]
In general: 
- [x] Require config works properly
- [x] Doesn’t refresh when turned keyRefreshOn is false
- [x] no keys
- [x] no keyservers
- [x] broken key servers

Works over Tor
- [x] dirmngr
- [x] with torsocks
- [x] works with socks arguments

Works not over Tor
- [x] works with socks arguments

**Comment by rosatolen** [comment]
What version of Gpg is this...

**Comment by chelseakomlo** [comment]
We should probably test above and below 2.1.

**Comment by chelseakomlo** [comment]
Cool. We did both above and below 2.1 in Windows? If so we should close this :)
