### ISSUE TITLE
Testing Arch

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/enigmail#50]
In general: 
- [x] Require config works properly
- [x] Doesn’t refresh when turned keyRefreshOn is false
- [x] no keys
- [x] no keyservers
- [x] broken key servers

Works over Tor
- [x] dirmngr
- [x] with torsocks
- [x] works with socks arguments

Works not over Tor
- [x] works with socks arguments

**Comment by rosatolen** [comment]
What's weird is that when Tor mode is enabled and Tor is not available on the system, I cannot make simple requests like `gpg2 --recv-keys <keyId>`. I get this failure message:
gpg: keyserver receive failed: Invalid argument
