### ISSUE TITLE
Fix addMacPaths

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#52]
Needs to be compatible with other distributions of GPG for Mac OS X.

**Comment by rosatolen** [comment]
https://sourceforge.net/p/gpgosx/docu/Download/

**Comment by natalieesk** [comment]
We realised that we can use the resolveToolPath from GPG Agent to find torsocks/2 and it is possible for the user to override the gpgagent path in the UI so we don't need AddMacPaths for these purposes any more.
