### ISSUE TITLE
Investigate gpg4win --version command arguments

### ISSUE THREAD

**Issue by rosatolen** [twtiger/enigmail#53]
args = ["--version", "--version", "--batch", "--no-tty", "--charset", "utf-8", "--display-charset", "utf-8"];

vs

args = ["--version"];

**Comment by yakiradixon** [comment]
Removing the other arguments was my mistake, and they need to be put back in. 

Initially I didn't see a change in the version information output with two --version arguments, but the second version argument is necessary to get the true path for gpg4win. 

I think the arguments should be reordered, though. When I run the command 

```
gpg2 --version --version --batch --no-tty --charset foo --display-charset foo
```

I see no output about foo being an invalid charset. But the command 

```
gpg2 --batch --no-tty --charset foo --display-charset foo --version --version
```

Will show me output about foo being an invalid charset.

**Comment by rosatolen** [comment]
Also, on Win8.1 with Gpg4win 2.3.2, the output is not different if `--batch", "--no-tty", "--charset", "utf-8", "--display-charset", "utf-8"` are before or after --version.

**Comment by rosatolen** [comment]
Associated commit: d41d2de2a22eeaea3422d56ce9bfe54689321e57
